# Generated by Django 5.1.2 on 2024-10-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.SmallIntegerField()),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('correo_usuario', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
