# Generated by Django 5.1.4 on 2025-01-10 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id_fuente', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fuente_activa', models.BooleanField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id_boletin', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100)),
                ('ciudad_tratada', models.CharField(max_length=100)),
                ('tematica', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='pdfs/')),
                ('fuente_boletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuente', to='tasks.fuente')),
            ],
        ),
    ]
